services:
  api:
    build: .
    ports:
      - "6969:6969"
    environment:
      - DOCKER_COMPOSE=true
  db:
    image: "postgres:15"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
