services:
  api:
    build: .
    ports:
      - '6969:6969'
    environment:
      - DOCKER_COMPOSE=true
    depends_on:
      - db
  db:
    image: 'postgres:15'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
